config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts do
  	resources :comments
  end
  root 'posts#index'
  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.email == "admin@admin" # you can add any condition
        can :manage, :all
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

			if @comment.save
				redirect_to post_path(@post)
			else
				redirect_to new_user_session_path
			end
		
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end 

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :category)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author= comment.user.email.split('@')[0]
	.buttons
		- if current_user!= nil
			- if comment.user.email ==  current_user.email
				= link_to "Editar", edit_post_comment_path(comment.post, comment)
				= link_to "Deletar", [comment.post, comment], method: :delete, data: { confirm: "Tem certeza?" }
			

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment
	= f.submit

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@post, @comment]) do |f| 
	= f.input :comment
	= f.submit

app/views/layouts/application.html.haml
!!!
%html 
%head
  %title CineForum
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  %link{ rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Lato", type: "text/css" }
  %link{ rel: "stylesheet", href: "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" }
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header.main_header.clearfix
    .wrapper
      #logo 
        %p= link_to "CineForum", root_path
        %p= link_to image_tag("logo.png"), root_path
      #buttons
        - if user_signed_in? 
          = link_to "Nova Postagem", new_post_path
          = link_to "Sair", destroy_user_session_path, method: :delete, class:"navbar-item"
          -if current_user!= nil && current_user.email == "admin@admin"
            = link_to "Administracao", '/admin', as: 'rails_admin', class:"navbar-item"
        - else
          = link_to "Registrar", new_user_registration_path
          = link_to "Entrar", new_user_session_path

  .wrapper    
    %p.notice= notice
    %p.alert= alert

  .wrapper  
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :category
  = f.input :content
  = f.submit

app/views/posts/edit.html.haml
%h1 Edit Post
= render 'form'
= link_to "Cancelar", post_path

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post
			%h2.title= link_to post.title, post
			%p.date
				Publicado Há
				= t(time_ago_in_words(post.created_at))
				por
				= post.user.email.split('@')[0]
				

app/views/posts/new.html.haml
%h1 Postagens
= render 'form'

app/views/posts/show.html.haml
#post_content 
	%h1= @post.title
	%h2= @post.category
	%p= @post.content

	#comments
		%h3
			Publicacao feita por:
		%h4 
			= @post.user.email.split('@')[0]
			<br>
			<br>
		%h2
			= @post.comments.count
		
			Comentarios
		= render @post.comments
		
		= render "comments/form"
	%br/
	%hr/
	%br/	
	- if current_user!= nil
		-if @post.user_id == current_user.id
			= link_to "Editar", edit_post_path(@post), class: "button"
			= link_to "Deletar", post_path(@post), method: :delete, data: { confirm: "Tem certeza que quer deletar a postagem ?" }, class: "button"